### ISSUE TITLE
[MODEL] Приложение не видит скрипты

### ISSUE THREAD

**Issue by anry-das** [captim/Gradebook#6]
При деплое приложения не выполняются скрипты создания структуры БД - приложение не находит соотвующих файлов

**Comment by captim** [comment]
Не знаю в чем проблема. Скачал проект в другую папку и все работает. Скрипты запускаются

**Comment by anry-das** [comment]
попробуй в БД все удалить и снова запустить приложение

**Comment by captim** [comment]
Удалил. Скрипт сработал.

**Comment by anry-das** [comment]
ок
